-- Run this SQL in your Supabase SQL Editor to support the new persistent features
-- (Updated with specific table names as per request)

-- 1. Create 'paper_extractor_votes' table to prevent double-voting (persists across restarts)
create table if not exists paper_extractor_votes (
  id bigint generated by default as identity primary key,
  image_id bigint not null,
  ip_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optimize lookups
create index if not exists pe_votes_image_ip_idx on paper_extractor_votes (image_id, ip_hash);

-- 2. Create Chats Table
create table if not exists paper_extractor_chats (
  id bigint generated by default as identity primary key,
  country text,
  msg text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Leaderboard Table
create table if not exists paper_extractor_leaderboard (
  country text primary key,
  score bigint default 0,
  chat_count bigint default 0
);

-- 4. Create Images Table (Stores Metadata for uploaded/extracted images)
create table if not exists paper_extractor_images (
  id bigint generated by default as identity primary key,
  doi text,
  image_hash text,
  storage_path text,
  country text,
  likes bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: Ensure you have a Storage Bucket named 'paper_images' created in Supabase Storage.
