-- Run this SQL in your Supabase SQL Editor to support the new persistent features

-- 1. Create 'votes' table to prevent double-voting (persists across restarts)
create table if not exists votes (
  id bigint generated by default as identity primary key,
  image_id bigint not null,
  ip_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Optimize lookups
create index if not exists votes_image_ip_idx on votes (image_id, ip_hash);

-- 2. Ensure your other tables exist (Reference)
/*
create table if not exists chats (
  id bigint generated by default as identity primary key,
  country text,
  msg text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists leaderboard (
  country text primary key,
  score bigint default 0,
  chat_count bigint default 0
);

create table if not exists images (
  id bigint generated by default as identity primary key,
  doi text,
  image_hash text,
  storage_path text,
  country text,
  likes bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
*/
